### ISSUE TITLE
db2_bind_param(): Describe Param Failed in zendtech/ibmitoolkit/ToolkitApi/Db2supp.php

### ISSUE THREAD

**Issue by tprinty** [zendtech/IbmiToolkit#101]
I am getting this message when attempting to call make a call using PgmCall();

It is failing on 
$params = array(
            array('position' => 1, 'name' => "internalKey", 'inout' => DB2_PARAM_IN),
            array('position' => 2, 'name' => "controlKey",  'inout' => DB2_PARAM_IN),
            array('position' => 3, 'name' => "inputXml",    'inout' => DB2_PARAM_IN),
            array('position' => 4, 'name' => "outputXml",   'inout' => DB2_PARAM_OUT),
        );
        
        // bind the four parameters
        foreach ($params as $param) {
            **$ret = db2_bind_param ($crsr, $param['position'], $param['name'], $param['inout']);**
            if (!$ret) {
                // unable to bind a param. Set error and exit
                $this->setStmtError($crsr);
                return false;
            }
        }

Is there anything that I need to tell my server team so I can use this?  I am trying to make this call from a webserver and not the AS400 itself.

**Comment by alanseiden** [comment]
@tprinty Let us know what kind of server you're running the code on (e.g. Windows, Linux...) and please confirm, are you using IBM's Db2 Connect product to connect the PHP server to the IBM i?

**Comment by tprinty** [comment]
Hello,

I am running my code on a Linux server. DB2 connect product is installed.  As I am developing in a local working area and using Zend APIGILITY (note not use Zend server) . I run my server with the command

php -S 0.0.0.0:8080 -ddisplay_errors=1 -dextension=/usr/lib/php/20151012/ibm_db2.so -t public public/index.php

**Comment by alanseiden** [comment]
@tprinty Did you resolve this issue or is it still open? Sorry we didn't have a quick answer when you asked. ODBC is now a viable option both on and off the IBM i and is recommended.

**Comment by alanseiden** [comment]
@tprinty We are closing this issue due to its age, but please let us know if you still get this error from the ibm_db2 module when attempting to bind an inout parameter to a stored procedure (in this case, an XMLSERVICE stored procedure) using the DB2 Connect product from a Linux server.
