### ISSUE TITLE
Take advantage of GitHub Projects + Issues to better community involvement.

### ISSUE THREAD

**Issue by jbh** [zendtech/IbmiToolkit#105]
Communities contribute more when they know what needs contributing. Documentation for IBM i Toolkit is poor, and that's putting it kindly.

I suggest that a Documentation project be created for IBM i Toolkit. Tasks/Issues can be created and easily delegated to or picked up by the community.

**Comment by jbh** [comment]
#71 and #23 related.

I also think using the `good first issue` label would be good for documentation issues to encourage community contribution.

**Comment by alanseiden** [comment]
We've added numerous examples in the last few years and are regularly adding more. Contributions are still welcome but I am closing this issue.
