### ISSUE TITLE
Fatal error: Interface 'ToolkitApi\ToolkitInterface' not found in Toolkit.php on line 19

### ISSUE THREAD

**Issue by jordiwes** [zendtech/IbmiToolkit#111]
Basic program call in PHP doesn't work for me anymore:
require_once('ToolkitApi/ToolkitService.php');
$tkobj = ToolkitService::getInstance($connection, null, null, 'odbc');

throws error above with call stack:
    0.2271     424632   2. ToolkitService::getInstance() /home/ALAN/php/tkodbc.php:25
    0.2271     425008   3. spl_autoload_call() /home/ALAN/php/ToolkitApi/ToolkitService.php:25
    0.2271     425056   4. {closure:/home/ALAN/php/ToolkitApi/autoload.php:3-56}() /home/ALAN/php/ToolkitApi/ToolkitService.php:25
    0.2311     703544   5. require_once('/home/ALAN/php/ToolkitApi/Toolkit.php') /home/ALAN/php/ToolkitApi/autoload.php:51

**Comment by alanseiden** [comment]
6739f176aab248bd327742b650ae80d96501819d
