### ISSUE TITLE
When using the toolkit from PHP, and the called RPG program crashes, the toolkit seems to submit a second try , which crashes as well.  

### ISSUE THREAD

**Issue by BelovedIncrease** [zendtech/IbmiToolkit#176]
Example form PHP. 
$tkConnection->setToolkitServiceParams(array('stateless'=>true));
$result = $tkConnection->PgmCall('S21INMVCL', 'AULXXP3', $params, NULL, NULL);

Message are sent to Qsysopr.  
Answered with Dump 
RPG program restarts and tries again.

**Comment by alanseiden** [comment]
@BelovedIncrease Are you sure your application isn't doing the second try, or the browser perhaps? The toolkit doesn't retry to my knowledge.

Either way, please create a debug log and post it here by adding to your array of options:
`$tkConnection->setToolkitServiceParams(array('stateless'=>true, 'debug'=>true, 'debugLogFile' =>’/any-path/tkit_debug.log'));
`
or use the setOptions alias, which is just a simpler name for the same method:
`$tkConnection->setOptions(array('stateless'=>true, 'debug'=>true, 'debugLogFile' =>’/any-path/tkit_debug.log'));
`


Either way, choose the path/file you want to use. 
Make sure your user profile has write permissions to the log file or directory it's in (if log not created yet). Thank you.

**Comment by BelovedIncrease** [comment]
Thanks Alan.  Log is on...debug = true, 
                and I cleared out previous data.  
"/usr/local/zendphp7/var/log/tkit_debug.log"  

Before asking Github, I checked with Websmart(fresche). 
        They do not believe the PHP is calling twice. 
The flow is PHP  does toolkit calls CLP sets libl, and calls RPG. 
QSYSOPR error is answered with Dump.  CL is answered with Dump. 
Program runs again.  Posting occurring in RPG happens twice. 
QSYSOPR error is answered with Dump.  CL is answered with Dump. 

Note no retry message opportunities. 
 

At 3PM, I get to test again.  I will be glad to toss the log then. 
Again, thanks for the review. 





From:   "Alan Seiden" ***@***.***>
To:     "zendtech/IbmiToolkit" ***@***.***>
Cc:     "BelovedIncrease" ***@***.***>, "Mention" 
***@***.***>
Date:   12/03/2021 10:53 AM
Subject:        Re: [zendtech/IbmiToolkit] When using the toolkit from 
PHP, and the called RPG program crashes, the toolkit seems to submit a 
second try , which crashes as well.   (Issue #176)



@BelovedIncrease Are you sure your application isn't doing the second try, 
or the browser perhaps? The toolkit doesn't retry to my knowledge.
Either way, please create a debug log and post it here by adding to your 
array of options:
$tkConnection->setToolkitServiceParams(array('stateless'=>true, 
'debug'=>true, 'debugLogFile' =>?/any-path/tkit_debug.log')); 
or use the setOptions alias, which is just a simpler name for the same 
method:
$tkConnection->setOptions(array('stateless'=>true, 'debug'=>true, 
'debugLogFile' =>?/any-path/tkit_debug.log')); 
Either way, choose the path/file you want to use.
Make sure your user profile has write permissions to the log file or 
directory it's in (if log not created yet). Thank you.
?
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 



Confidentiality Notice:
This transmission (including any attachments) may contain confidential 
information belonging to the sender and is intended only for the use of 
the party or entity to which it is addressed. If you are not the intended 
recipient, you are hereby notified that any disclosure, copying, 
distribution, retention or the taking of action in reliance on the 
contents of this transmission is strictly prohibited. If you have received 
this transmission in error, please immediately notify the sender and erase 
all information and attachments.

**Comment by alanseiden** [comment]
@BelovedIncrease Thanks. Oh, could you check your Apache access log, if this was a web request? Try to verify that there was no double-request there, and no HTTP 408 being returned, which sometimes causes browsers to retry.

**Comment by alanseiden** [comment]
@BelovedIncrease Is this still an issue?

**Comment by BelovedIncrease** [comment]
, 
How kind of you to reply. 
You have previously responded regarding Toolkit second tries: 


Due to ERP install deadlines, it has not be addressed. 
I hope it's looked at soon. 

Thanks for checking.

BTW, Beloved Increase is just my name translated from Hebrew.


David Pearson
  937-663-9370
 




From:   "Alan Seiden" ***@***.***>
To:     "zendtech/IbmiToolkit" ***@***.***>
Cc:     "BelovedIncrease" ***@***.***>, "Mention" 
***@***.***>
Date:   01/14/2022 02:50 PM
Subject:        Re: [zendtech/IbmiToolkit] When using the toolkit from 
PHP, and the called RPG program crashes, the toolkit seems to submit a 
second try , which crashes as well.   (Issue #176)



@BelovedIncrease Is this still an issue?
?
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 
You are receiving this because you were mentioned.Message ID: 
***@***.***>




Confidentiality Notice:
This transmission (including any attachments) may contain confidential 
information belonging to the sender and is intended only for the use of 
the party or entity to which it is addressed. If you are not the intended 
recipient, you are hereby notified that any disclosure, copying, 
distribution, retention or the taking of action in reliance on the 
contents of this transmission is strictly prohibited. If you have received 
this transmission in error, please immediately notify the sender and erase 
all information and attachments.

**Comment by alanseiden** [comment]
Closing issue until more information provided.
