### ISSUE TITLE
Show how to handle varchars in sample code

### ISSUE THREAD

**Issue by NattyNarwhal** [zendtech/IbmiToolkit#179]
It's not obvious how to handle a program that takes in a varchar. Regular char won't work well, as the length prefix will confuse it. There's also the possibilities where the buffers are smaller. Deal with two and four byte varchars.

Adding an int16/int32 parameter and then a max length of varchar character parameter seems to work, but is this really ideal? What about `varying`? If it handles varchar, then we should make that clear, and if it doesn't, also make that clear.

**Comment by alanseiden** [comment]
We only need to specify 'on' or '4' for the sixth parameter ('varying') on AddParameterChar. Varying = VARCHAR.

**Comment by alanseiden** [comment]
From XMLSERVICE change log (http://www.youngiprofessionals.com/wiki/index.php/XMLService/XMLSERVICEChangeLog):
```
1.6.11 (new 07–18–2012) 	

    BUG: added varying(4) support for RPG V6+ 10A varying(4) — thanks Steph
        Toolkit wrapper (php): see Alan for availability

             Notes: Alan, i believe wrapper needs to flow "varying" parm add to data element 
            varying='on|off|2|4', 
            where varying='on' legacy remains 2 byte length for no impact current scripts 
            Something like this ...
            $ToolkitServiceObj->AddParameterChar('both', 10, 'ZZVARY', 'myVary', 'Ranger', 'on'); // 6th --'on'--is for varying
            -- new -- 
            $ToolkitServiceObj->AddParameterChar('both', 10, 'ZZVARY', 'myVary', 'Ranger', '4'); // 6th --'4'--is for varying(4)

        RAW XML (xmlservice):

              *       <data type='data types' 
              *          [dim='n' varying='on|off|2|4' enddo='label' setlen='label' offset='label'
              *           hex='on|off' before='cc1/cc2/cc3/cc4' after='cc4/cc3/cc2/cc1']> 1.6.8

**Comment by alanseiden** [comment]
Use of VARCHAR has now been documented  on the data types page:
https://github.com/zendtech/IbmiToolkit/blob/master/samples/data-types.md
