### ISSUE TITLE
Limitations in Data Area functionality

### ISSUE THREAD

**Issue by alanseiden** [zendtech/IbmiToolkit#26]
In the DataArea class of iToolkitService: readDataArea() and writeDataArea() produce an error when the data area is type *DEC. The underlying commands (e.g. CHGDTAARA) need to be told the data type, but the toolkit doesn't specify, causing the default type, character, to be used. Also, the CHGDTAARA command requires that numeric values be quoted, even when the data area is of type *CHAR, but we don't do this, leading to more errors. 

See #19 for a related issue. A solution to #19, if done with the present issue in mind, could resolve it as well.

**Comment by chukShirley** [comment]
@alanseiden So we just need to make the toolkit allow users to specify parameter types sort of like we do with program calls?

```php
<?php
$dataArea = new DataArea();
$dataArea->readDataArea(1, '*ALL', '*DEC');
// Adds a third parameter for the type associated with the _value_ parameter
```

**Comment by alanseiden** [comment]
My opinion now is that the PHP toolkit was too ambitioius in creating wrappers for such functionality, because it's difficult to cover every case. Better to provide examples that others could follow.

**Comment by chukShirley** [comment]
So instead of having a specific DataArea class just show users how to accomplish the same tasks with CL commands?

**Comment by jordiwes** [comment]
I would say yes :)

**Comment by alanseiden** [comment]
A new IBM i SQL Service provides functionality to read data areas from SQL: https://www.rpgpgm.com/2019/06/using-data-areas-with-sql.html

That's part of the solution.

**Comment by alanseiden** [comment]
Closing in favor of other solutions for working with data areas.
