### ISSUE TITLE
Refactor to one class per file

### ISSUE THREAD

**Issue by adamculp** [zendtech/IbmiToolkit#3]
There are a few files that contain multiple classes. To follow modern convention these should be broken up so each file contains a single class.

Examples:
ToolkitServiceParameter.php
iToolkitService.php
CW/cwclasses.php

**Comment by adamculp** [comment]
This should remain open until PSR-0 and PSR-4 qualifications are met.

**Comment by chukShirley** [comment]
I think this was fixed in https://github.com/zendtech/IbmiToolkit/pull/47

**Comment by adamculp** [comment]
Sorry for my confusion. I will close and if needed I will open another later. Thanks for your hard work.

**Comment by chukShirley** [comment]
No worries. I can always use people checking behind me. I made a lot of changes and could very well have left something out.
