### ISSUE TITLE
Add log information: toolkit class location

### ISSUE THREAD

**Issue by alanseiden** [zendtech/IbmiToolkit#33]
In ExecuteProgram() in ToolkitService.php, various information is logged when debug mode is turned on. Add logging of the toolkit class file location (full path of ToolkitService.php) so that users will know where the toolkit is running from, because there are sometimes several copies. This addition would reduce confusion.

The line to update:
$this->debugLog("\nExec start: " . date("Y-m-d H:i:s") . "\nVersion of toolkit front end: " . self::getFrontEndVersion() ."\nIPC: '" . $this->getInternalKey() . "'. Control key: $controlKeyString\nHost URL: $url\nExpected output size (plugSize): $plugSize or $outByteSize bytes\nInput XML: $inputXml\n");

Add __FILE__, changing the line to:
$this->debugLog("\nExec start: " . date("Y-m-d H:i:s") . "\nVersion of toolkit front end: " . self::getFrontEndVersion() ."\nToolkit class: '" . __FILE__
. "'\nIPC: '" . $this->getInternalKey() . "'. Control key: $controlKeyString\nHost URL: $url\nExpected output size (plugSize): $plugSize or $outByteSize bytes\nInput XML: $inputXml\n");

**Comment by chukShirley** [comment]
Resolved in https://github.com/zendtech/IbmiToolkit/pull/61
