### ISSUE TITLE
Stateless flag from toolkit.ini is not used

### ISSUE THREAD

**Issue by Scott-Cam** [zendtech/IbmiToolkit#38]
When the flag for stateless is set to true in the toolkit.ini the value is not used by the ToolkitService.php but the value in the $_options array is used instead.  The code should be updated to use the values from the toolkit.ini if they are present.

**Comment by alanseiden** [comment]
It's used by the CW. Scott created a later pull request to create an equivalent setting for the non-CW regular toolkit.
