### ISSUE TITLE
Refactor file names to match class names

### ISSUE THREAD

**Issue by adamculp** [zendtech/IbmiToolkit#4]
There are some files where the filename doesn't match the class name contained within.  This needs to be refactored so that a class contained wtihin a file should be the same name as the file, minus the file extension.

Examples:
ToolkitPCML.php != ToolkitPcml
ToolkitServiceParameter.php != ProgramParameter
ToolkitServiceXML.php != XMLWrapper

**Comment by adamculp** [comment]
This should remain open, until PSR-0 and PSR-4 qualifications are met.

**Comment by chukShirley** [comment]
Should be met after recent commits.

**Comment by adamculp** [comment]
Sorry. Will review and verify. Thanks.

**Comment by adamculp** [comment]
Sorry for my confusion. I will close and if needed I will open another later. Thanks for your hard work.
