### ISSUE TITLE
Add additional integer types

### ISSUE THREAD

**Issue by alanseiden** [zendtech/IbmiToolkit#40]
The toolkit is missing 8- and 16-byte (short) integers, both signed and unsigned, on the PHP side of the toolkit (they are allowed in XMLSERVICE):

Suggested code to add to ProgramParameter.php would be something like:

```php
class Int8Param extends ProgramParameter{

function __construct($io,  $comment,  $varName = '', $value, $dimension=0, $by='', $isArray = false, $labelSetLen = null) {

parent::__construct(  '3i0', $io, $comment, $varName, $value, 'off', $dimension, $by, $isArray, $labelSetLen, null  );

return $this;

}

}
```

```php
class UInt8Param extends ProgramParameter{

function __construct($io,  $comment,  $varName = '', $value, $dimension=0, $by='', $isArray = false, $labelSetLen = null) {

parent::__construct(  '3u0', $io, $comment, $varName, $value, 'off', $dimension, $by, $isArray, $labelSetLen, null  );

return $this;

}

}
```

```php
class Int16Param extends ProgramParameter{

function __construct($io,  $comment,  $varName = '', $value, $dimension=0, $by='', $isArray = false, $labelSetLen = null) {

parent::__construct(  '5i0', $io, $comment, $varName, $value, 'off', $dimension, $by, $isArray, $labelSetLen, null  );

return $this;

}

}
```

```php
class UInt16Param extends ProgramParameter{

function __construct($io,  $comment,  $varName = '', $value, $dimension=0, $by='', $isArray = false, $labelSetLen = null) {

parent::__construct(  '5u0', $io, $comment, $varName, $value, 'off', $dimension, $by, $isArray, $labelSetLen, null  );

return $this;

}

}
```
Suggested code for ToolkitService.php to use the above classes would be something like:

/**
* @param $io
* @param $comment
* @param string $varName
* @param string $value
* @param int $dimension
* @return Int8Param
*/
static function AddParameterInt8( $io, $comment, $varName = '', $value = '', $dimension = 0 ) {
return new Int8Param ($io, $comment, $varName, $value, $dimension);
}

/**
* @param $io
* @param $comment
* @param string $varName
* @param string $value
* @param int $dimension
* @return UInt8Param
*/
static function AddParameterUInt8( $io, $comment, $varName = '', $value = '', $dimension =0) {
return new UInt8Param ($io, $comment, $varName, $value, $dimension) ; // removed erroneous "off"
}

/**
* @param $io
* @param $comment
* @param string $varName
* @param string $value
* @param int $dimension
* @return Int16Param
*/
static function AddParameterInt16( $io, $comment, $varName = '', $value = '', $dimension = 0 ) {
return new Int16Param ($io, $comment, $varName, $value, $dimension);
}

/**
* @param $io
* @param $comment
* @param string $varName
* @param string $value
* @param int $dimension
* @return UInt16Param
*/
static function AddParameterUInt16( $io, $comment, $varName = '', $value = '', $dimension =0) {
return new UInt16Param ($io, $comment, $varName, $value, $dimension) ; // removed erroneous "off"
}

**Comment by chukShirley** [comment]
Added in PR https://github.com/zendtech/IbmiToolkit/pull/60
