### ISSUE TITLE
Optionally allow toolkit to generate parameters from D Specs

### ISSUE THREAD

**Issue by chukShirley** [zendtech/IbmiToolkit#43]
There's a lot to flesh out here, and it may not even be feasible. But it seems possible to allow toolkit users to optionally specify if they want the toolkit to retrieve the D specs from the RPG source member and generate the parameters rather than manually creating them in PHP. Here are my initial thoughts (open to correction):

## **Proposed Format**
![](https://programmersprogress.files.wordpress.com/2015/05/screen-shot-2015-05-06-at-11-04-19-am-2.png)

## **The Process**
The RpgSource class would just have parameters for library, source file, and source member

![](https://programmersprogress.files.wordpress.com/2015/05/screen-shot-2015-05-06-at-11-09-09-am-2.png)

The ToolkitService::GenerateParams() method would use XMLSERVICE to retrieve the source file at the location specified in the above array. I don't know the specifics of how XMLSERVICE could be used to accomplish this, but I remember someone (Tony or Alan) at COMMON telling me that it's possible. Once PHP has the source member it would just be a matter of mimicking the parsing behavior of the D Spec Tool (converting JS to PHP). Once the D specs have been converted to PHP method calls then the method could use PHP's eval() function to actually run the generated PHP code and return the $param array. Something like the following:

![](https://programmersprogress.files.wordpress.com/2015/05/screen-shot-2015-05-06-at-11-10-51-am-2.png)

## **Advantages**
1. PHP developers wouldn't be responsible for keeping the toolkit parameters in sync with RPG D specs. Refactoring would only require changing the D specs in the RPG source file.
2. PHP developers wouldn't have to know the details of the RPG D specs in order to be able to call a program.

## **Disadvantages**
1. Doubling the number of XMLSERVICE requests will mean slower performance, but as an optional feature it will be a choice that each developer can make.  **Update: The source member could be cached. This way the performance hit won't really occur until the cache needs refreshing.**

Full code can be found in the following Gist:
https://gist.github.com/chukShirley/4b36776a70efcdc758b9

XMLSERVICE on Bitbucket:
https://bitbucket.org/inext/xmlservice-rpg

D Spec Tool:
http://yips.idevcloud.com/Samples/DSpecTool/application/map/map

**Comment by phpdave** [comment]
Could add caching to elimate the double call to xmlservice.

**Comment by phpdave** [comment]
Have a config variable that controls cache on and off. (Off in development and on for production)

**Comment by phpdave** [comment]
Could set the time period between refreshing the cache.   

Might want a batch process that will create the parameters based on an entire library.

**Comment by phpdave** [comment]
Run sh command through the xmlservice such as 

cat mylib.lib/program.file

**Comment by chukShirley** [comment]
Good thinking. I updated the gist to check cache before using XMLSERVICE to run the cat command. Still have to figure out the XML syntax for running a shell command. Is there already a toolkit method for that?

**Comment by jordiwes** [comment]
Why not use PHP ftp commands to bring in the source file? Seems easier for first go around.
The other issue is that parms will often need to be populated. How will that be accomplished?

**Comment by chukShirley** [comment]
Maybe it's easier than I'm thinking, but I just wanted to bypass the ftp credentials part. I'm certainly open to trying it though. 

And yes the parms will need to be able to be populated existing values will need to be mapped somehow. Not sure yet how that should happen. Maybe a mapping class or method receives an associative array and expects the names to match exactly with the parsed D spec variables and parameter list. Open to suggestions.

**Comment by alanseiden** [comment]
If I'm not mistaken, these ideas assume that the D Spec Mapper can be perfected, so perhaps the first step would be to perfect the D Spec Mapper so that its output requires no adjustment as is required today. I believe Tony wrote it as a "one pass" mapper, generating essentially "helpful hints" as to the proper parameters, but with a second pass through the source code, it could do a more exact job.

**Comment by chukShirley** [comment]
I'm definitely assuming that the D Spec Mapper can be perfected. If it can't then this feature won't be worth pursuing. Perhaps we should speak to Tony to find out how feasible it is to perfect it.

**Comment by clarkphp** [comment]
Source code is here, and unfortunately, I can't say I've looked at it closely yet:
http://yips.idevcloud.com/Samples/DSpecTool/js/xmlservice_v13.js

**Comment by chukShirley** [comment]
I'm going to close this issue. It seems like a lot of work for a small convenience. Additionally this would only ensure that the parameters are generated from the **source member**. However, the **compiled object** is what XMLSERVICE is actually interacting with. Thus toolkit users would have to ensure that the source member is always in sync with the compiled object, which isn't feasible.
