### ISSUE TITLE
Git branching strategy

### ISSUE THREAD

**Issue by alanseiden** [zendtech/IbmiToolkit#51]
Using the master branch for development has caused confusion among end users, who tend to assume that the master branch is production-ready. The resulting bugs and errors create a poor experience for end users.

Consider creating a development branch for development and using the master branch as a latest stable release.

Input requested.

**Comment by chukShirley** [comment]
I'm for it! +1

**Comment by clarkphp** [comment]
Don't consider that. Let's do it! :-)  Having master always represent
"production-ready" is typical in many organizations. Would a simplified
git-flow make sense?

**Comment by kingharrison** [comment]
I agree! +2

**Comment by jbh** [comment]
+1

Also, here is an article for different git-flows: https://www.atlassian.com/git/tutorials/comparing-workflows/

The feature branch model is a nifty one https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow

But as mentioned by @clarkphp, a simplified git-flow might be better for this type of project: https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow

**Comment by chukShirley** [comment]
Done.
