### ISSUE TITLE
Write unit tests

### ISSUE THREAD

**Issue by alanseiden** [zendtech/IbmiToolkit#72]

**Comment by chukShirley** [comment]
This will presumably be a continual requirement. Does this issue refer specifically to "cover the existing code with unit tests"?

**Comment by alanseiden** [comment]
Implies that 2.0 code is easily tested. Let's make sure is.

**Comment by alanseiden** [comment]
We are well on the way, with some tests and a more easily tested Toolkit class. We are adding tests as features are enhanced.
