### ISSUE TITLE
Thoughts for 2.0

### ISSUE THREAD

**Issue by alanseiden** [zendtech/IbmiToolkit#83]
**Separate these ideas into separate issues having milestone 2.0.**

Most important one (in Alan's view): Replace the terminology and implementation of "internal key" and "stateless" to make connections easier to understand. Many users doing it wrong (causing terrible problems) because they didn't understand the IPC concept (/tmp/alan) and because the PHP toolkit 1.x defaults to stateful mode using the same key for everyone (/tmp/Toolkit). Tony suggests creating a main class (Base) that specific connection mode classes could inherit from. Name them well. Alan suggests "privateJob" or the like for stateful connections. Hide the IPC concept. Perhaps accept a key that the toolkit adds to /tmp.  

Make changes to respond to XMLSERVICE 2.0 (iAYE). Possibly change from XML to JSON if it looks good on the XMLSERVICE side.

Improve methods to be better OO style. e.g. fewer arguments in the method signature, fit better in OO applications and ZF. Perhaps more fluent interfaces. Use "good" patterns so that the toolkit won't appear alien to OO developers.

Call transports "adapters," etc. Real OO patterns, events. As ZF did.

Try to reduce the amount of code to make it easier for people to contribute to it. If PHP 7 helps simplify, could use that, even to require PHP 7.

True REST APIs of a more refined level (headers etc.).

These could result in b/c breaks so let's save for 2.0.

**Comment by chukShirley** [comment]
It might be useful for people involved in the design process of the eventual 2.0 package to at least skim the book [_Principles of Package Design_](https://leanpub.com/principles-of-package-design) by Matthias Noback (Symfony guy). I confess that I'm only halfway through it, but so far it establishes good guidelines when making design decisions regarding packages like the toolkit.

**Comment by alanseiden** [comment]
All desired tasks in this issue have been re-entered as individual issues tagged with milestone 2.0. Those issues are: #87, #88, #89, #90, #92, and #93.
