### ISSUE TITLE
Exception when class in autoloader not found

### ISSUE THREAD

**Issue by mleiv** [zendtech/IbmiToolkit#96]
When integrating IbmiToolkit into a magento 2 project, I got this exception:

`Exception #0 (Exception): Notice: Undefined index: CybersourceFacade in /var/www/public_html/vendor/zendtech/ibmitoolkit/ToolkitApi/autoload.php on line 48`

It is easily resolved by checking that the class exists in the array before creating the $file variable. I will add a pull request.

**Comment by fabiopellati** [comment]
on  1.7.1  release note it is written that this problem is resolved but is not true for that version

**Comment by chukShirley** [comment]
This appears to be a separate issue from what the 1.7.1 release notes refer to. @alanseiden Hadn't merged this fix when 1.7.1 was tagged. Thus, a new release is needed to include the fix from @mleiv.

**Comment by chukShirley** [comment]
Just tagged 1.7.2.

**Comment by alanseiden** [comment]
@mleiv Could you please verify that the 1.7.2 tagged release resolves the issue?

**Comment by chukShirley** [comment]
@mleiv Any word on whether this issue is resolved?

**Comment by alanseiden** [comment]
Fixed in an older release. This issue should no longer occur.
