### ISSUE TITLE
Stateless option breaks toolkit in ZS 9.0.1 Beta

### ISSUE THREAD

**Issue by kingharrison** [zendtech/IbmiToolkit#98]
Installing the Zend Server 9 preview I found that I was getting an error while trying to run my application. I went through and narrowed it down to the stateless option in the toolkit. When I commented it out (which I assume means the default setting is false) it worked fine. Here is my configuration with stateless commented out. 

```<?php

namespace RPG\Service\Factory;

use Zend\ServiceManager\FactoryInterface;
use Zend\ServiceManager\ServiceLocatorInterface;

use ToolkitApi\Toolkit;


/**
 * Class ToolkitFactory
 * @package RPG\Service\Factory
 */
class ToolkitFactory implements FactoryInterface
{
    /**
     * @param ServiceLocatorInterface $serviceLocator
     * @return mixed
     */
    public function createService(ServiceLocatorInterface $serviceLocator)
    {
        $dbAdapter = $serviceLocator->get('Zend\Db\Adapter\Adapter');
        $dbAdapter->getDriver()
            ->getConnection()
            ->connect();
        $dbConn = $dbAdapter->getDriver()
            ->getConnection()
            ->getResource();
        //require_once("ToolkitService.php");
        // pass database connection into toolkit instantiation
        //$tkConn = \ToolkitService::getInstance($dbConn, DB2_I5_NAMING_ON); // cheating here by hard-coding naming mode
        $tkConn = new Toolkit($dbConn, DB2_I5_NAMING_ON);
        $tkConn->setOptions(array(
            //'stateless' => true
        ));
        //$tkConn->setToolkitServiceParams( array( 'debug' => true) );
        return $tkConn;
    }
}```

**Comment by alanseiden** [comment]
Commenting out your stateless option is not a good workaround, because then the toolkit will default to stateful mode with /tmp/Toolkit as a default IPC (internalkey). What error did you receive in stateless mode?

**Comment by kingharrison** [comment]
When I uncomment the stateless line so that stateless is true here is the error I get in the error log:

[09-Feb-2017 17:35:18 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function ToolkitApi\logThis() in /usr/local/zendphp7/var/apps/http/10.5.49.30/9292/02.02.16_15/vendor/zendtech/ibmitoolkit/ToolkitApi/Toolkit.php:871
Stack trace:
#0 /usr/local/zendphp7/var/apps/http/10.5.49.30/9292/02.02.16_15/vendor/zendtech/ibmitoolkit/ToolkitApi/Toolkit.php(783): ToolkitApi\Toolkit->makeDbCall(false, '512K', '*cdata *here', '<?xml version="...', false)
#1 /usr/local/zendphp7/var/apps/http/10.5.49.30/9292/02.02.16_15/vendor/zendtech/ibmitoolkit/ToolkitApi/Toolkit.php(958): ToolkitApi\Toolkit->ExecuteProgram('<?xml version="...', false)
#2 /usr/local/zendphp7/var/apps/http/10.5.49.30/9292/02.02.16_15/vendor/zendtech/ibmitoolkit/ToolkitApi/Toolkit.php(663): ToolkitApi\Toolkit->sendXml('<?xml version="...', false)
#3 /usr/local/zendphp7/var/apps/http/10.5.49.30/9292/02.02.16_15/module/K3sbase/Module.php(118): ToolkitApi\Toolkit->pgmCall('AC_SIGNON', 'WEB_5OBJ', Array, NULL, NULL)
#4 [internal function]: K3sbase\Module->onBootstrap(Object(Zend\Mvc\MvcEvent))
# in /usr/local/zendphp7/var/apps/http/10.5.49.30/9292/02.02.16_15/vendor/zendtech/ibmitoolkit/ToolkitApi/Toolkit.php on line 871

**Comment by kingharrison** [comment]
Here is the toolkit debug log. The first section is when stateless is on. IT looks like it just never executes. Second one is off and seems tor un fine. 

[tkit_debug.log.txt](https://github.com/zendtech/IbmiToolkit/files/764517/tkit_debug.log.txt)

**Comment by kingharrison** [comment]
Looking at the error line it seems like if you turn on stateless it has an issue connecting to the database. And then no error comes off. Code section related to line 871 reference in line:

$outputXml = $this->db->execXMLStoredProcedure($this->conn, $sql, $bindArray);
        if (!$outputXml) {
            // if false returned, was a database error (stored proc prepare or execute error)
            // @todo add ODBC SQL State codes

            // If can't find stored proc for ODBC: Database code (if any): S1000. Message: [unixODBC][IBM][System i Access ODBC Driver][DB2 for i5/OS]SQL0440 - Routine IPLUG512K in XMLSERVICE not found with specified parameters.
            //Warning: odbc_prepare(): SQL error: [unixODBC][IBM][System i Access ODBC Driver][DB2 for i5/OS]SQL0440 - Routine IPLUG512K in XMLSERVICE not found with specified parameters., SQL state S1000 in SQLPrepare in /usr/local/zend/ToolkitAPI/Odbcsupp.php on line 89
            $this->cpfErr = $this->db->getErrorCode();
            $this->setErrorMsg($this->db->getErrorMsg());

            $errorReason = $this->getErrorReason($plugSize);

            logThis($errorReason);
            die($errorReason);
        }

**Comment by Scott-Cam** [comment]
PHP Fatal error: Uncaught Error: Call to undefined function 
ToolkitApi\logThis()

The call to logThis() is the cause of that error which is stopping the 
real error message from being shown, can you comment it out and see what 
is in $errorReason?

Scott

**Comment by kingharrison** [comment]
I commented it out and it said this:

Toolkit request failed. Review the database code and message. Database code (if any): '22504'. Message:

**Comment by kingharrison** [comment]
I also dumped this variable: $this->db->getErrorMsg()

and got this message:

"Mixed data or UTF-8 data not properly formed."

**Comment by kingharrison** [comment]
I did a var_dump on the $bindArray called on line 859 and this was put out:

array(5) { ["internalKey"]=> bool(false) ["controlKey"]=> string(12) "*cdata *here" ["inputXml"]=> string(709) " " ["outputXml"]=> string(0) "" ["disconnect"]=> bool(false) } 

I did it on the a ZS 8.5.5 install where stateless connection works and the output was:

array(5) { ["internalKey"]=> string(1024) " " ["controlKey"]=> string(12) "*cdata *here" ["inputXml"]=> string(709) " " ["outputXml"]=> string(524288) " " ["disconnect"]=> bool(false) }

**Comment by kingharrison** [comment]
Ok, the $this->VerifyInternalKey() on line 771 returns NULL. 

So l looked at the verifyInternalKey and on line 1881 and if it is stateless it was setting to '', so I set it to ' ' and now it worked. I have absolutely no idea of the implications of that though, but its working as stateless now.

**Comment by chukShirley** [comment]
@kingharrison Line 1881 of which file?

**Comment by kingharrison** [comment]
Toolkit.pho

-King Harrison
Sent from iPhone
Please excuse all typos




On Sun, Feb 12, 2017 at 5:18 PM -0500, "Chuk Shirley" <notifications@github.com> wrote:












@kingharrison Line 1881 of which file?

**Comment by chukShirley** [comment]
Which version are you using? Line 1881 of Toolkit.php is blank https://github.com/zendtech/IbmiToolkit/blob/master/ToolkitApi/Toolkit.php#L1881

**Comment by kingharrison** [comment]
It was 1881 when I was probably editing and messing around. My bad. But it works now on ZS9. 

Know what doesnt work? Field names with a # or $

**Comment by alanseiden** [comment]
The message "Mixed data or UTF-8 data not properly formed" is probably the crux of the issue, some kind of encoding issue. Stateless mode means the toolkit runs in a Db2 job, so perhaps there was a CCSID or other encoding issue in the Db2 or ibm_db2 configuration.

**Comment by alanseiden** [comment]
Looks like this issue was specific to King's configuration or data.
